server:
  port: 10015
############################################################自定义配置区#################################################
# 无需鉴权的URL
url-blocking:
  ignores:
    - /api/rest/aurora-user-services/login
    - /user/register
    - /user/getCode/**
#########################################################Token相关信息配置###############################################
# tonken加密密钥
# sign: 11111
# token过期时间
# expiry_date: 233